version: '2'
services:
  teamspeak:
    image: polinux/teamspeak:latest
    ports:
      - "9987:9987/udp"
      - "30033:30033"
      - "10011:10011"
    environment:
      - TS3SERVER_LICENSE=accept
    volumes:
      - /srv/quickload/docker-volumes/teamspeak:/opt/teamspeak
    restart: unless-stopped
